spring:
  application:
    name: GAE-DAS
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gae-das
    username: root


das:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password:

  # 增量索引配置
  store:
    # 文件存储
    file:
      enable: true
      # 文件名
      path: index/incr.idx

logging:
  level:
    org.fh.gae.das: debug
  pattern:
    console: "[%d{HH:mm:ss}] [%thread] %-5level %logger{36} - %msg%n"

