spring:
  application:
    name: GAE-DAS

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gae-das
    username: root


das:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password:

    # binlog文件名
    binlog-name: ""
    # binlog偏移量, -1表示从当前位置开始
    position: -1


  # 增量索引配置
  store:
    # 文件存储
    file:
      enable: true
      # 文件名
      path: incr.idx

    kafka:
      enable: false
      topic: gae-idx
      addr: 10.150.182.11:8092

logging:
  level:
    org.fh.gae.das: debug
  pattern:
    console: "[%d{HH:mm:ss}] [%thread] %-5level %logger{36} - %msg%n"

